/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresentationTemplateIdRouteImport } from './routes/presentation.$templateId'
import { Route as DocumentTemplateIdRouteImport } from './routes/document.$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationTemplateIdRoute = PresentationTemplateIdRouteImport.update({
  id: '/presentation/$templateId',
  path: '/presentation/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentTemplateIdRoute = DocumentTemplateIdRouteImport.update({
  id: '/document/$templateId',
  path: '/document/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/document/$templateId': typeof DocumentTemplateIdRoute
  '/presentation/$templateId': typeof PresentationTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/document/$templateId': typeof DocumentTemplateIdRoute
  '/presentation/$templateId': typeof PresentationTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/document/$templateId': typeof DocumentTemplateIdRoute
  '/presentation/$templateId': typeof PresentationTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/document/$templateId' | '/presentation/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/document/$templateId' | '/presentation/$templateId'
  id: '__root__' | '/' | '/document/$templateId' | '/presentation/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentTemplateIdRoute: typeof DocumentTemplateIdRoute
  PresentationTemplateIdRoute: typeof PresentationTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation/$templateId': {
      id: '/presentation/$templateId'
      path: '/presentation/$templateId'
      fullPath: '/presentation/$templateId'
      preLoaderRoute: typeof PresentationTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$templateId': {
      id: '/document/$templateId'
      path: '/document/$templateId'
      fullPath: '/document/$templateId'
      preLoaderRoute: typeof DocumentTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentTemplateIdRoute: DocumentTemplateIdRoute,
  PresentationTemplateIdRoute: PresentationTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
